"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-08 19:54:08.648717

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "child",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("avatar", sa.String(length=16), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("tts_rate", sa.Float(), nullable=False),
        sa.Column("show_text", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "passage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("reference", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("chunk_unit", sa.String(length=10), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("pass_threshold", sa.Float(), nullable=False),
        sa.Column("k_required", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "spelling_list",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("pass_threshold", sa.Float(), nullable=False),
        sa.Column("carry_forward", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "list_assignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("round_no", sa.Integer(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=True),
        sa.Column("passed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["child_id"], ["child.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["list_id"], ["spelling_list.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("list_id", "child_id"),
    )
    with op.batch_alter_table("list_assignment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_list_assignment_child_id"), ["child_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_list_assignment_list_id"), ["list_id"], unique=False)

    op.create_table(
        "passage_assignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("passage_id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("current_section", sa.Integer(), nullable=False),
        sa.Column("clean_full_runs", sa.Integer(), nullable=False),
        sa.Column("pass_threshold", sa.Float(), nullable=False),
        sa.Column("k_required", sa.Integer(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=True),
        sa.Column("passed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["child_id"], ["child.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["passage_id"], ["passage.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("passage_id", "child_id"),
    )
    with op.batch_alter_table("passage_assignment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_passage_assignment_child_id"), ["child_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_passage_assignment_passage_id"), ["passage_id"], unique=False
        )

    op.create_table(
        "section",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("passage_id", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["passage_id"], ["passage.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("section", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_section_passage_id"), ["passage_id"], unique=False)

    op.create_table(
        "spelling_word",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(length=80), nullable=False),
        sa.Column("sentence", sa.Text(), nullable=False),
        sa.Column("homophone", sa.Boolean(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("for_child_id", sa.Integer(), nullable=True),
        sa.Column("carried_from_list_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["carried_from_list_id"], ["spelling_list.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["for_child_id"], ["child.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["list_id"], ["spelling_list.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("spelling_word", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_spelling_word_for_child_id"), ["for_child_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_spelling_word_list_id"), ["list_id"], unique=False)

    op.create_table(
        "line_stat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assignment_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("struggle_score", sa.Float(), nullable=False),
        sa.Column("consecutive_correct", sa.Integer(), nullable=False),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("miss_count", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("word_misses", sa.JSON(), nullable=False),
        sa.Column("prev_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["assignment_id"], ["passage_assignment.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["section_id"], ["section.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assignment_id", "section_id"),
    )
    with op.batch_alter_table("line_stat", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_line_stat_assignment_id"), ["assignment_id"], unique=False
        )

    op.create_table(
        "recite_attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assignment_id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=40), nullable=False),
        sa.Column("section_ids", sa.JSON(), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("missed_words", sa.JSON(), nullable=False),
        sa.Column("matched", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("verdict", sa.Boolean(), nullable=False),
        sa.Column("override", sa.Boolean(), nullable=True),
        sa.Column("peeked", sa.Boolean(), nullable=False),
        sa.Column("audio_seconds", sa.Float(), nullable=True),
        sa.Column("stt_ms", sa.Integer(), nullable=True),
        sa.Column("state_before", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assignment_id"], ["passage_assignment.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recite_attempt", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recite_attempt_assignment_id"), ["assignment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recite_attempt_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "spelling_attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assignment_id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("typed", sa.Text(), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assignment_id"], ["list_assignment.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["word_id"], ["spelling_word.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("spelling_attempt", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_spelling_attempt_assignment_id"), ["assignment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_spelling_attempt_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "word_stat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assignment_id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("struggle_score", sa.Float(), nullable=False),
        sa.Column("consecutive_correct", sa.Integer(), nullable=False),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("miss_count", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("prev_score", sa.Float(), nullable=False),
        sa.Column("carried", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["assignment_id"], ["list_assignment.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["word_id"], ["spelling_word.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assignment_id", "word_id"),
    )
    with op.batch_alter_table("word_stat", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_word_stat_assignment_id"), ["assignment_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("word_stat", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_word_stat_assignment_id"))

    op.drop_table("word_stat")
    with op.batch_alter_table("spelling_attempt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_spelling_attempt_created_at"))
        batch_op.drop_index(batch_op.f("ix_spelling_attempt_assignment_id"))

    op.drop_table("spelling_attempt")
    with op.batch_alter_table("recite_attempt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recite_attempt_created_at"))
        batch_op.drop_index(batch_op.f("ix_recite_attempt_assignment_id"))

    op.drop_table("recite_attempt")
    with op.batch_alter_table("line_stat", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_line_stat_assignment_id"))

    op.drop_table("line_stat")
    with op.batch_alter_table("spelling_word", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_spelling_word_list_id"))
        batch_op.drop_index(batch_op.f("ix_spelling_word_for_child_id"))

    op.drop_table("spelling_word")
    with op.batch_alter_table("section", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_section_passage_id"))

    op.drop_table("section")
    with op.batch_alter_table("passage_assignment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_passage_assignment_passage_id"))
        batch_op.drop_index(batch_op.f("ix_passage_assignment_child_id"))

    op.drop_table("passage_assignment")
    with op.batch_alter_table("list_assignment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_list_assignment_list_id"))
        batch_op.drop_index(batch_op.f("ix_list_assignment_child_id"))

    op.drop_table("list_assignment")
    op.drop_table("spelling_list")
    op.drop_table("passage")
    op.drop_table("child")
    # ### end Alembic commands ###
